openimis/openimis-be-core_py

core/management/commands/compilemessages.py, locale/en/LC_MESSAGES/django.po, setup.py
This command sadly has to duplicate a lot of the stock command's code to inject "locale" folders within each module.
This commands is in the core module because the root module has no application of itself to store the command.
=> OMT-206 add custom compilemessages command

core/models.py
The issue comes from the User, InteractiveUser and TechnicalUser all inheriting from the base AbstractUser and having a _u delegation. This means that Django cannot guess from User that it has to request a password when using createsuperuser. So we're allowing an empty password by default.
This obviously requires to set the password in a second command. The changepassword was not working either because when setting the password, it was properly delegated to the underlying TechnicalUser but that user was not saved, only User. I therefore added a save() function to delegate the saving of the underlying object if it had already been created (it has an id).
I am a bit afraid of side effects with the auto provisioning of users and other use cases.
=> Fix createsuperuser/changepassword

core/models.py
Pull request related to https://github.com/openimis/openimis-be-policyholder_py/pull/5 - allowing to filter by using "is_deleted" field. It is a small change. Now user can obtain non-deleted records by filtering "is_deleted"=False or deleted records by using "is_deleted"=True. As I wrote in pull id=5 for PolicyHolder repo I encountered some problems with filtering by default value of is_deleted=False and query doesn't work for is_deleted=True. That fix simply allow to filter also deleted record (so as to use "checkbox to show deleted" from PolicyHolder wiki in "PolicyHolder search page" section)
=> OFS-99: enabling to filter deleted or non-deleted records

core/models.py
Please also merge this change in Core module. It is really significant for models with foreign keys. I've detected this bug with Rafal during updating PolicyHolder with changing only locations Id. Without that params django-dirty-fields doesn't detect changes in objects related with foreign keys. But with this one "is_dirty" behaves properly.
=> OFS-99: django-dirty-fields bug - applied additional param in 'is_dirty'

core/gql/gql_mutations/base_mutation.py
Could you merge this fix, because mutation log shows an error, but delete end successfully? @rstencel reported me this error. I had to change this. In mutation logs it must be 'None' so as to have status=2(success). Otherwise mutation log show "status=1" - (error) if we have output text.  
When the text is sent instead of None to the mutation_log - there is an error - mutation status has status=1 even if record is deleted (should be status 2).
=> OFS-119: fixing bug related to mutation log in 'delete' mutation

core/utils.py
In that PR I want to merge the function written in utils.py in Core module which return filters date_valid_from/date_valid_to on 4 scenarios:
- default scenario
- only date valid to (end) set
- only date valid from set
- both filters set
=> OFS:159: fix - filtering dates valid from/to (start, end date)

core/datetimes/ad_datetime.py, core/models.py
In that pull request I want to fix some issues in Core module with HistoryModel and HistoryBusinessModel. There are three changes, two requested by Patrick @delcroip and one detected by me with using core datetime and date fields type instead of default django ones (model.DateTime etc).
1. using core Date and DateTime type instead of default django one according to the clues given by BlueSquare ("openIMIS dates management (backend and frontend)" in https://openimis.atlassian.net/wiki/spaces/OP/pages/1938489348/2020-11-19+Developer+training+material+Q+A).
2. Replaced entity should not be updatable (requested by Patrick)
3. When a replacement entity is deleted, the link should be removed from replaced entity so a new replacement could be generated (requested by Patrick)
To the point 1 - the …
=> OFS-178: replace issues in HistoryModel/BusinessModel and datetime issue in that models 

core/models.py
In that PR I want to fix issue with deleting detected by @delcroip.
=> OFS-178: ObjectDoesNotExist exception - use filter instead of get

core/websocket/abstract_websocket_client.py
Previously method only checked if instance of socket existed, now it additionally checks if it has the connected flag set to True.
=> OAI-29: Improved connection check method

core/signals.py
In that PR I want to add overriden Signal class to the Core module according to the idea from https://openimis.atlassian.net/wiki/spaces/OP/pages/1730740234/Calculations+Module and https://stackoverflow.com/questions/10017567/possible-to-change-order-of-django-signals
=> OFS-136: adding overridden Signal class so as to add priority

core/apps.py, core/models.py, core/schema.py
TICKETS: OFS-229 https://openimis.atlassian.net/browse/OFS-229 - create and update mutation
and partially - with adding perms - https://openimis.atlassian.net/browse/OFS-230 - OFS-230
In that PR I want to add create and update Role graphQl mutations. Also I added perms for that and another future mutations in apps.py of Core module.
Moreover I had to modify uuid field in Role model into 
`uuid = models.CharField(db_column='RoleUUID', max_length=36, default=uuid.uuid4, unique=True)`
with adding "default=uuid.uuid4, unique=True" because without it the uuid for a new Role wasn't created properly and there were some issues on backend during creating a whole new Role.
The rest of mutations for Role will be merged in another PR.
=> OFS-229: createRole and updateRole mutations

core/utils.py
Ticket - https://openimis.atlassian.net/browse/OFS-254 - 1 issue with filtering validity for FS entities 
In that PR I want to add function to append filtering validity or in case of setting special flag - returning no filters if in graphQl somebody want to not filter by default one.
It will be used for schema in FS modules. (HistoryBusinessModel)
=> OFS-254: adding new validity flag for business entities FS

README.md, core/gql/gql_mutations/__init__.py, core/gql/gql_mutations/mutation_by_filter.py
Developed as part of OAI-49. Additional generic decorator allows to execute mutations not by uuids but by filters. 
It can be added to OpenIMISMutation.async_mutate.
=>  OAI-49: Added decorator for using filters in muatations

core/gql/gql_mutations/__init__.py, core/gql/gql_mutations/mutation_by_filter.py
TICKET: https://openimis.atlassian.net/browse/OFS-285
=> OFS-285: changes regarding bulk action for FS entities

core/gql/gql_mutations/mutation_by_filter.py
TICKET: https://openimis.atlassian.net/browse/OFS-292 
part related to 1st issue. "1. Fix custom graphQl filters in  'mutation by filter':
a) date_valid_from/date_valid_to
b) amountTo/From.
In that activity functions from utility should be used/reused."
Date Valid From/To will applied per default only valid entities. Similar as isDeleted=False
In the future this action will be triggered by sending signal to 'Contract module'. I marked TODO to emphasize this idea to implement in the nearest future.
=> OFS-292: fixing bulk actions with amount/date valid filters

core/apps.py
part of TICKET https://openimis.atlassian.net/browse/OE0-4
added missing perms for 'Claim Administrator' and 'Enrolment Officers'  according to https://openimis.atlassian.net/wiki/spaces/OP/pages/1775173658/openIMIS+Authorities
I put TODO to be discussed later @dragos-dobre : 
- consider moving that roles related to ClaimAdmin and EnrolmentOfficer into modules related to that type of user for example: 
EnrolmentOfficer -> policy module, ClaimAdmin -> claim module etc
=> OE0-4: added missing perms for ClaimAdmin and EOfficer

core/schema.py
TICKET: https://openimis.atlassian.net/browse/OE0-4
then we can show in perms another permissions not only related to graphQL etc.
=> OE0-4: change the way of checking config for permissions

core/jwt.py, core/jwt_authentication.py, core/schema.py
As discussed on Skype, move JWT token config modules to the core rather than main assembly module.
To be tested before merging.
=> Move JWT modules from main to core

core/jwt_authentication.py
hotfix for Ticket https://openimis.atlassian.net/browse/OE0-2 after deployment on modular-fs test server
I needed to remove this because when I was trying to make a request and send in RESTED client then I received CSRF error validation during callings some endpoints defined on modular. ""CSRF Failed: CSRF token missing or incorrect."" This should not enforce validating csrf during validation of auth header.
Affected environment: https://modular.fs.swisstph-mis.ch/
=> OE0-2: remove enforce_csrf validation after detecting issue on test server.

core/models.py
json.loads by defaut does not ensure that the data is loaded in the order specified in the custom config. The configuration order can be important in some cases (e.g. PolicyNotification module). Using OrderedDict solve this issue.
=> Json configuration loaded as OrderedDict

core/migrations/0015_missing_roles.py
TICKET: https://openimis.atlassian.net/browse/OE0-29
This migration should fix broken tests from this PR in api_fhir_r4 module.
=> OE0-29: added migration for put missing role for ClaimAdministrator

core/views.py
This is not exactly OMT-281 but being unable to connect with a claim administrator prevents the test at all.
As pointed out in the comment, by default, the rest framework will look for core.user_view permission among the numeric permissions of openIMIS and obviously deny access. Explicitly setting the permission on that specific view allows any authenticated user to view their own data, as intended. Unauthenticated users will still get a 403 response.
=> Cannot connect with non-admin user OMT-281

core/schema.py
We checked the create_roles_perms instead of create_users_perms
=> hotfix(Users): Wrong permissions checked when creating/updating users

core/models.py, setup.py
The cached_property would fail when called with HFID==0 (as happens in tblUsers that has no foreign key on this one)
=> OMT-281 follow-up when HFID is 0

core/abs_calculation_rule.py
The method was declared as `instance, *args` so calling calculate(instance=instance, *args) failed with unexpected parameter signal (first kwargs). Calling the method with instance=instance makes it a named argument, so you can't pass any positional argument after that. That proper way is for methods to accept both *args and **kwargs and then call with instance as positional, the *args will add more positional arguments and then **kwargs can be passed.
This makes the contract module test properly.
=> calc rule calculate() should not name first arg

core/services/__init__.py, core/services/base.py, core/services/userServices.py, core/services/utils/__init__.py, core/services/utils/serviceUtils.py, core/validation/__init__.py, core/validation/base.py, core/validation/objectExistsValidationMixin.py, core/validation/uniqueCodeValidationMixin.py
[https://openimis.atlassian.net/browse/OPL-54](https://openimis.atlassian.net/browse/OPL-54)
Changes:
- Moved BaseService and BaseModelValidation to from `invoice` to `core` module (to reuse in fhir `module` for subscription resource)
=> OPL-54: Move BaseService and BaseModelValidation to core module

core/models.py
[https://openimis.atlassian.net/browse/OPL-57](https://openimis.atlassian.net/browse/OPL-57)
This PR depends on https://github.com/openimis/openimis-be-core_py/pull/109
Changes:
- Added `args` and `kwargs` to `super().save()` and `super().delete()` calls
- Added "popping" of username provided to `save` and `delete` method from arguments before sending it back to ORM.
=> OPL-57: Fix compability of HistoryModel with django rest framework

README.md, core/schema.py
[https://openimis.atlassian.net/browse/OTC-717](https://openimis.atlassian.net/browse/OTC-717)
Changes:
- Added `ParsedJSONString` allowing to mimic GQL automatic camel case to snake case conversion in GQL embedded JSON fields
- Added `mutation_extensions` allowing to pass extra data to signals connected with a mutation. This allow new modules to extend existing mutations without modifying them. This field is not passed to the original mutation
=> OTC-717 Implement generic way to extend GQL Models

core/services/utils/serviceUtils.py, core/test_services.py
[https://openimis.atlassian.net/browse/OTC-701](url[)](https://openimis.atlassian.net/browse/OTC-701)
Changes:
- Added `check_permissions`, decorator allowing checking permissions before service actions
=> OP-701 Added check permissions service helper

core/schema.py
Ticket: https://openimis.atlassian.net/browse/OP-950
Changes:
- Backend throws exception is username of a new user is already taken.
=> OP-950: Backend now checks if username is already taken in new user.

core/models.py, core/schema.py
Developed for [OP-949](https://openimis.atlassian.net/browse/OP-949)
Change extends graphql users query by additional parameter regionIds, which allows fetching users from multiple regions. 
Note: This PR doesn't provide additional security checks. We should additionally investigate whether users can retrieve data to which they are not authorized (e.g. from outside their assigned regions).
=> OP-949: Query users by multiple regions

core/schema.py
Ticket: https://openimis.atlassian.net/browse/OP-1394
Will not work without: 
https://github.com/openimis/openimis-be_py/pull/133
Changes:
- Removed mention of django-rest-framework-rules library.
=> OP-1394: DRF rules package removed.

core/test_services.py
Ticket:
https://openimis.atlassian.net/browse/OTC-1080
Changes:
- added deletion of records in UserRole table before deleting Users. Due to FK constraits it was raising an error of deleting one of two related tables that had dependent values.
=> OTC-1080: added deletion of dependent tabels before user tabel is deleted

README.md, core/apps.py, core/custom_filters/__init__.py, core/custom_filters/custom_filter_registry_point.py, core/custom_filters/custom_filter_wizard_interface.py, core/custom_filters/custom_filter_wizard_storage.py
TICKET: https://openimis.atlassian.net/browse/CM-68
PR delivers:
- Interface for CustomFilterWizard
- Registry point to obtain from particular module (on its apps.py file) information about implemented above interfaces while core module initialization
- Core Hub (storage) to build output how to build filters for particular object type 
The way how it works is below. This is the concept how it could work. Based on mocked fixed implementation of interfaces in social_protection module (real logic will be implemented within CM-69 ticket). If you have some ideas how to improve this solution at this stage please let me know in the review comments. 
- mocked implementation of interfaces for creation of custom filters
- mocked custom_filter.py file in policy module
- some operations on that …
=> CM-68: Develop core logic for handling custom filters - BE

core/custom_filters/custom_filter_wizard_interface.py, core/custom_filters/custom_filter_wizard_storage.py, core/gql/export_mixin.py, core/test_helpers.py
TICKET: https://openimis.atlassian.net/browse/CM-162
=> CM-162: improve custom filter applying into queryset in query and exports

core/migrations/0020_add_missing_fields_to_django_scheme.py, core/models.py
- Changed UserGroup model `managed` metafield to `False` as the UserGroup is a model for auto generated many to many table and `managed = True` causes django to try and create a second table.
- Changed name capitalization for UserGroup table to the correct one to avoid any errors related to table names. Postgres database by default makes table names case insensitive, but it can be forced to check the capitalization.
=> Fixed UserGroup model table name and managed

core/schema.py
Ticket:https://openimis.atlassian.net/browse/ONI-132
Changes: 
- Added code for handling of autogeneration of fields during mutation.
=> ONI-132: Changing mutation code to handle autogeneration.

core/schema.py
https://openimis.atlassian.net/browse/CM-296
This PR adds ability to use additional params with custom filters.
=> CM-296: add additional params to the custom filters

core/utils.py
Ticket: https://openimis.atlassian.net/browse/ONI-174
Changes:
- Added util to remove permissions from role
=> ONI-174: Add util to remove permission from a role.

core/services/userServices.py, core/views.py
TICKET: https://openimis.atlassian.net/browse/CQI-80
Solving issues with CSRF : https://github.com/openimis/openimis-be-core_py/pull/226/commits/275f3f962925f5598e62bd5a3e2540692301d391, https://github.com/openimis/openimis-be-core_py/pull/226/commits/1d907f79f80ee59d305245cc12dbcca176dd0077
Addressing Password-Related Issues: One of the issues at the service level is not related to setting the password  but hardcoded encoded in base64 'stored_password' https://github.com/openimis/openimis-be-core_py/blob/ddc31917db208af5e66c4f020ee24e3df8b615a9/core/services/userServices.py#L52. In the legacy version, setting the password for a User was optional, and this approach is retained here to maintain compatibility.  For sure this part of code and mechanism can be improved, but at this stage we …
=> CQI-80: OWASP A01:2021-Broken Access Control - openimis-be-core_py BE

core/tests.py
TICKET: https://openimis.atlassian.net/browse/CQI-104
COMMENT: We optimized the regular expression pattern by reducing backtracking. In this optimized pattern, we're using positive lookbehind (?<=[a-z0-9]) to ensure that the position we're looking at is preceded by a lowercase letter or a digit, and then we're using a positive lookahead (?=[A-Z]) to ensure that it's followed by an uppercase letter. This should help reduce backtracking and improve performance, addressing the security concern.
=> CQI-104: fixed compiling regex pattern

core/apps.py
Ticket: https://openimis.atlassian.net/browse/ONI-48
Changes:
- Added setting in core module to allow for easy reference of secondary calendar defined on the backend.
=> ONI-48: Added setting for secondary calendar.

core/schema.py, core/tasks.py
chatGTP doc:
Your tested version of coerce_mutation_data appears to be more comprehensive and handles various cases including nested input types. Here's a brief explanation of the key aspects:
Handling Nested Input Types: The method recursively handles nested input types by calling itself if the field type is a custom input object.
Checking Field Type: Instead of using field.type, it directly checks the class of the field (field.__class__). This allows more precise checking and handling of different types, such as graphene.List or custom input types.
Custom Input Types: For custom input types, it handles coercion by calling coerce_mutation_data recursively with the inner input class.
Logging: It includes logging for cases where a key is not found in the input class. This can be helpful …
=> test fix async

core/apps.py
Ticket:
https://openimis.atlassian.net/browse/CQI-154
This ticket was created to increase number of characters available in the username field. It has no minimal limit set, we discussed this on the meeting with stakeholders.
=> CQI-154: increased length of username to 12

core/jwt_authentication.py, core/middleware.py, core/models/user.py, core/schema.py, core/services/userServices.py
BEFORE MERGING, CHECK THIS:
https://github.com/openimis/openimis-be_py/pull/243
Ticket:
https://openimis.atlassian.net/browse/CQI-153
Changes:
- lockout mechanism checks for numbers of attempts
- no token is being checked when authenticating, it allows to properly handles errors
- axes is added as a lockout mechanism tool
Tested:
- user can login
- user cannot login from given IP if numbers of tries exceeded the limit
- user with wrong credentials is informed, there is no "UNKOWN ERROR" anymore
PoC:
=> Feature/cqi 153: add lockout mechanism for login functionality

core/models/user.py, core/utils.py
Ticket:
https://openimis.atlassian.net/browse/CQI-148
Related: 
https://github.com/openimis/openimis-be_py/pull/244
Changes:
- password policy is set
- password cannot contain any dictionary or typical password
- password must contain small leter, capital, number and special characters
- password is at least 12 characters long
Those are default value, it will be configurable for each implementation with be_py PR.
1. Proper error handling for password_validator
2. Proper error handling for typical password and dictionaries
3. User can be created if the password is strong:
=> CQI-148: strenghten password policy for new user

core/schema.py
Ticket:
https://openimis.atlassian.net/browse/CQI-164
Changes:
- administrator cannot deprovision himself (IMIS Administrator role)
1. admin can deprovision some other roles
2. attempt of deleting his own admin role will be prohibited
=> CQI-164: administrator cannot deprovision himslef

core/middleware.py
Changes:
- moved security headers to PROD because it caused issue on some local instances with admin panel. Some browser don't add Origin when running the application from localhost.
- changed referrer header
=> Moved security headers for PROD only
