- core/schema.py
When an exception was raised in the mutation, the mutationlog would just stay hanging forever. I added a catch-all that logs the exception and marks the mutation as failed.
> Add try/except around async_mutate

- README.md
- core/admin.py
- core/apps.py
- core/datetimes/ad_datetime.py
- core/datetimes/shared.py
- core/fields.py
- core/models.py
- core/schema.py
- core/security.py
- core/tasks.py
- core/utils.py
The tricky part is the order_by management with the newest version of Graphene.
Took the opportunity to enable LGTM on this.
> Omt 204 components upgrade

- core/models.py
- setup.py
This pull request delivers a whole new Model in models.py - HistoryModel
> OFS-25: Added new model HistoryModel

- core/models.py
- core/utils.py
In that pull request I want to merge minor changes related to PolicyHolder module changes. I had to add custom filter to check if object is deleted or not.
> OFS-89: changes related to "PolicyHolder" module - new custom filter

- core/gql/gql_mutations/base_mutation.py
- core/models.py
In that pull request I want to merge some changes related to "replace" mutation and changes connected with this operation. 
I also changed the replace mutation in base mutations.
Furthermore I had to make changes in Core module in model so as to allow update fields if somebody want to change certain fields. 
Another pull requests related to this issue: 
- policy holder: https://github.com/openimis/openimis-be-policyholder_py/pull/12
- contribution plan: https://github.com/openimis/openimis-be-contribution_plan_py/pull/9
> OFS-118: fixing replace mutations and replace in model

- README.md
- core/__init__.py
- core/custom_lookups.py
The change is due to the requirement for filtering by json_ext field in AI Project, but the filter itself is generic enough to be used also in other modules.
> OAI-23: Added new lookup filter for json fields

- core/models.py
I want to merge small changes related to bug detected by Rafal @rstencel in replacing (detexted in replace mutation in CPB). I have to check the date vs datetime and now the comparison between date vs datetime if there is date is now possible.
Please merge this so as to @rstencel can continue work on replace ContributionPlanBundle etc.
Thx for detecting bug @rstencel
> OFS-152: fixing date comparing issue detected on replace mutation

- core/utils.py
In that PR I want to merge filter validation for date_valid in new business model so as to fix issue described by @rstencel  in OFS-159 ticket.
> OFS-159: filter validity for new business models

- README.md
- core/__init__.py
- core/websocket/__init__.py
- core/websocket/abstract_websocket_client.py
- core/websocket/async_websocket_client.py
- core/websocket/base_websocket_client.py
- setup.py
Part of [OAI-29](https://openimis.atlassian.net/browse/OAI-29)
> OAI-29: Added websocket client features

- core/utils.py
Changes in filtering validity of business models requested by Patrick in https://github.com/openimis/openimis-be-core_py/commit/ab5a0bdee71a09f7d39aac86c93c7c98869eb1b9.
> OFS-159: changes in filters with date_end

- core/abs_calculation_rule.py
PR related to this ticket https://openimis.atlassian.net/browse/OFS-207 and wiki page - https://openimis.atlassian.net/wiki/spaces/OP/pages/1730740234/Calculations+Module - section "absCalculationRule class"
Static attributes/variables of class are that ones that are inside a class but outside any method (class variables). 
3 methods have the implementation in that class, the rest ones will be implemented in particular classes related to the calculation rules. They are marked as "abstractmethod".
> OFS-207: absCalculationRule class - implementation

- core/abs_calculation_rule.py
That PR should be merged after merging changes in ContributionPlan module (backend). - https://github.com/openimis/openimis-be-contribution_plan_py/pull/23
In that PR I want to change abstract class and change implementation of some methods because of some changes in calculation module.
> OFS-219: changes related to the calculation module

- core/apps.py
- core/gql_queries.py
- core/schema.py
TICKET: https://openimis.atlassian.net/browse/OFS-228 OFS-228
In that PR I want to add graphQl query for Role and the query for obtaining ConfigPerms so as to display that ones into frontend during developing frontend for Roles.
a) Example of retrieving Role with RoleRights assigned to the Role:
b) Example of retrieving perms config per module:
> OFS-228: graphQl for roles

- README.md
- core/schema.py
TICKET: https://openimis.atlassian.net/browse/OFS-229 - OFS-229
In that PR I want to add two graphQl mutations:
- deleteRole
- duplicateRole
I also update README.md file with description about graphQl for Role
> OFS:229: Delete and Duplicate graphQl mutations

- core/gql_queries.py
- core/schema.py
In that PR I want to replace "validity" into "show_historical" filter.
Also I want to include fixes wth displaying all perms available in modular app.That looks after that changes in that commit - https://github.com/openimis/openimis-be-core_py/commit/8aec4639b171c9b72a0399ed0c487a23f62ae477
> OFS-253: replace validity in role graphQl into show_historical

- core/gql_queries.py
- core/schema.py
Ticket https://openimis.atlassian.net/browse/OFS-254 - issue 4 flag "is system"
Filtering via "is_system" = Bolean instead of Int
> OFS:254: changes in is_system filtering

- README.md
Ticket - https://openimis.atlassian.net/browse/OFS-254 -2 Issue - write documentation for Contract module and specify abstractCalculationClass in core module.
In that PR I want to add into readme.md description of implemented ABSCalculationRule class.
> OFS-254: adding information about ABSCalculationRule

- core/schema.py
TICKET: https://openimis.atlassian.net/browse/OFS-258
I think this should solve both problems described in ticket. Let me know later @rstencel !
> OFS-258: fixes regarding flag is_system

- core/gql_queries.py
- core/models.py
TICKET: https://openimis.atlassian.net/browse/OFS-258
> OFS-258: solving problem with filtering show_historical

- core/models.py
OFS-258: issue with show_historical
> OFS-258: remove filter_queryset

- core/utils.py
- ValidityFrom cannot be null
- withtout end filter, get all item valid that the current date AND in the future
> Update default filter

- core/gql/gql_mutations/mutation_by_filter.py
backend part of TICKET: https://openimis.atlassian.net/browse/OFS-290
fixes regarding bulk actions when sb want to use 'uuids'.
> OFS-290: fixed bug with performing uuids bulk actions

- README.md
- core/gql_queries.py
- core/schema.py
- core/utils.py
Developed as part of: [OTC-289](https://openimis.atlassian.net/browse/OTC-289). 
New query returns list of available languages from tblLanguages.
> OTC-289: Added GQL Query for languages

- core/test_helpers.py
This is necessary for JWT auth to work properly and have all tests run successfully
> Add a password (&private key) to test user

- core/models.py
Changes:
- `HistoryModel` `uuid` property fixed to allow setting (required bu querying)
- `HistoryModelManager` added to map `uuid` property to `id` field
[https://openimis.atlassian.net/browse/OE0-64](https://openimis.atlassian.net/browse/OE0-64)
> OE0-64: Fixed HistoryModel uuid property

- core/schema.py
- core/services.py
Expose Query.enrolmentOfficers
> Save more fields of User, Officer & IUser when using Django

- README.md
- core/service_signals.py
- core/signals.py
TICKET: [OPL-13](https://openimis.atlassian.net/browse/OPL-13)
> OPL-13: Added decorators and functions for service signals

- core/gql/gql_mutations/base_mutation.py
More generic solution for BaseHistoryModelDeleteMutationMixin. It allows both id and uuid input.
> OPL-6: Fixed Base Delete Mutation

- README.md
- core/abs_calculation_rule.py
- core/migrations/0015_missing_roles.py
TICKET: https://openimis.atlassian.net/browse/OPL-26
Changes:
- new fields, methods in abstract calculation rule like get_convert_from_to, convert, run_convert.
> OPL-26: changes in abstract calculation class due to new calculation rule

- core/abs_calculation_rule.py
TICKET: https://openimis.atlassian.net/browse/OPL-31
> OPL-31: small changes regarding new converter in rule - contract to invoice

- core/models.py
The interactive user has a health facility without foreign key but the claim admin has a foreign key. This method encapsulates this and is needed for OMT-281 so that price lists are available.
We are dynamically loading the location module, so if it is not available, it will simply consider that there is no such limit.
> Facilitate access to health facility

- core/jwt_authentication.py
TICKET: https://openimis.atlassian.net/browse/OE0-79
I fixed issue that was reported when someone want to use 'api' instead of 'iapi' in "login" endpoint. I used 'REMOTE_USER_AUTHENTICATION' condition to check if we have 'api'. If no - standard approach with JWT token is used to authorize. 
Please verify this before merging.
> OE0-79: hotfix - issue on 'login' FHIR endpoint in 'api'

- core/jwt_authentication.py
TICKET: https://openimis.atlassian.net/browse/OE0-79
Improved yesterday's PR https://github.com/openimis/openimis-be-core_py/pull/92. Also fixed 'eval' .
> OE0-79: fixed solution with supporting 'basic auth'

- core/abs_calculation_rule.py
TICKET: https://openimis.atlassian.net/browse/OPL-52
> OPL-52: changes in 'run_calculation' to make bill calculation rules working

- core/test_helpers.py
This is used in contract module and maybe others
> Add a test helper for technical (super)user

- core/models.py
- core/services/base.py
[https://openimis.atlassian.net/browse/OPL-44](https://openimis.atlassian.net/browse/OPL-44)
Changes:
- Fixed exception handling in `BaseService` to include model name in output instead of a fixed value
> OPL-44: Create model and CRUD Services for Subscription

- README.md
- core/custom_lookups.py
Changes:
- Added `JsonContainsKey` lookup for `FallbackJSONField`. It wraps `key` as `"key":` and implements `contains` search for json fields
> OPL-92: Added JsonContainsKey custom lookup

- core/gql/gql_mutations/base_mutation.py
TICKET: https://openimis.atlassian.net/browse/OP-762
> OP-762: moved Null 'validity_to' assigment to the 'core'

- core/abs_calculation_rule.py
add calculate_if_active_for_object function
> calculate_if_active_for_object

- core/schema.py
The auto-provisioning of users was lost in the JWT port. This modifies the tokenAuth to provision before using the graphql_jwt method.
> Add user auto provisioning to JWT auth

- core/gql_queries.py
- core/scheduler.py
TICKET: [OP-811](https://openimis.atlassian.net/browse/OP-811)
> OP-811: Validity filtering for user districts

- README.md
- core/gql_queries.py
- core/scheduler.py
Part of [OTC-621](https://openimis.atlassian.net/browse/OTC-621). 
Actual implementation is entirely depending on assembly module, but core seems to be better suited for documentation.
> OTC-621: Added README entry for scheduled tasks implementation

- core/models.py
Part of TICKET: [OP-840](https://openimis.atlassian.net/browse/OP-840).
> OP-840: Added is_officer check to user

- core/gql_queries.py
- core/schema.py
Part of [OP-842](https://openimis.atlassian.net/browse/OP-842).
> OP-842: Added searching by system id for roles

- core/apps.py
- core/custom_lookups.py
- core/migrations/0013_users_api.py
- core/migrations/0016_add_last_login_on_interactive_user.py
- core/models.py
- core/schema.py
- setup.py
> Django 3.1

- core/apps.py
- core/forms.py
- core/schema.py
- core/services/userServices.py
- core/signals.py
- core/validation/obligatoryFieldValidation.py
Part of [OP-861](https://openimis.atlassian.net/jira/software/c/projects/OTC/boards/31?selectedIssue=OP-861)
> OP-861: Field contol added

- core/calendars/test_ad_calendar.py
- core/calendars/test_ne_calendar.py
- core/datetimes/test_ad_datetime.py
- core/datetimes/test_ne_datetime.py
- core/test_services.py
[https://openimis.atlassian.net/browse/OP-868](https://openimis.atlassian.net/browse/OP-868)
Changes:
- Changed handling of JSON fields from JSON strings to python dictionaties (Django 3.2 update)
- Fixed TestCase handling (added all missing calls to super.setUpClass, super.setUp, removed unecessary teardowns)
- Removed some unused code/comments/imports
- Fixed code formatting
> OP-868 Fix CI issues caused by Django 3.2 update

- core/models.py
Ticket: https://openimis.atlassian.net/browse/OP-860
Connected to: https://github.com/openimis/openimis-be-location_py/pull/38
Changes:
- has_perms() now returns true is user is a superuser
- is_superuser checks technical user 'superuser' flag
> OP-860: Superuser type checks in users.

- core/gql/gql_mutations/mutation_by_filter.py
Ticket: https://openimis.atlassian.net/browse/OP-936
Changes:
- Added support for exception message.
- Connected ticket: https://github.com/openimis/openimis-be-contract_py/pull/70
> OP-936: Added support for celery exceptions.

- core/schema.py
https://openimis.atlassian.net/browse/OP-1011
> OP-1011: modular IMIS: search for users gives double results

- core/schema.py
https://openimis.atlassian.net/browse/OP-1053
Changes:
- Added graphQL query for FE part in this PR: https://github.com/openimis/openimis-fe-admin_js/pull/43
> OP-1053: Graphql query for FE checks.

- core/schema.py
- core/services/roleServices.py
https://openimis.atlassian.net/browse/OP-1082
This PR adds validate_role_name in schema.py and adds roleServices to provide validation logic.
It is related to the pull request on frontend: https://github.com/openimis/openimis-fe-core_js/pull/84
> OP-1082: create backend logic to validate if role name is unique

- .github/workflows/openmis-module-test.yml
- core/models.py
Ticket: [OTC-797](https://openimis.atlassian.net/browse/OTC-797)
[OTC-797]: https://openimis.atlassian.net/browse/OTC-797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OTC-797: Added claim admin check to user

- .github/workflows/openmis-module-test.yml
- core/schema.py
- core/services/userServices.py
https://openimis.atlassian.net/browse/OTC-873
Changes:
- GQL added for validation of users email
- Update_or_create now checks for validity of the email
> OTC-873: GQL validation code.

- core/gql_queries.py
Ticket: https://openimis.atlassian.net/browse/OTC-811
Used by:
https://github.com/openimis/openimis-be-insuree_py/pull/47
Changes:
- Added generic validationGQL type with isValid status, error code and message.
> OTC-811: Generic ValidationGQL type added.

- core/schema.py
[https://openimis.atlassian.net/browse/OTC-843](https://openimis.atlassian.net/browse/OTC-843)
Changes:
- Added a way to pass an exception with errors array from async_mutate, so it can be logged with mutation id
- Updated return type of async_mutate
> OTC-843 Added a way to pass an exception with mutation errors

- core/schema.py
Ticket: https://openimis.atlassian.net/browse/OTC-876
Changes:
- Added permissions check for validity queries.
> OTC-876: Permissions check added in validation queries.

- core/schema.py
- locale/en/LC_MESSAGES/django.po
https://openimis.atlassian.net/browse/OTC-876
Changes:
- Fixed translations messages.
> OTC-876: Updated translations messages.

- core/gql_queries.py
- core/schema.py
- core/utils.py
https://openimis.atlassian.net/browse/OTC-878
> OTC-878: add permission to all gql mutations and queries

- core/schema.py
https://openimis.atlassian.net/browse/OTC-878
This PR fixes one change from already merged: https://github.com/openimis/openimis-be-core_py/pull/155
> OTC-878: remove authentication from resolve module configruation

- core/gql_queries.py
https://openimis.atlassian.net/browse/OTC-973
This PR comments perm checks that were causing issues.
Relates to: https://github.com/openimis/openimis-be-location_py/pull/63
> OTC-973: comment some permission checks to allow testing

- core/urls.py
- core/views.py
[https://openimis.atlassian.net/browse/OIF-2](https://openimis.atlassian.net/browse/OIF-2)
Changes:
- Added core/scheduled_tasks endpoint allowing logged in users to check currently scheduled tasks next execution date and handler functions
> OIF-2 Added scheduled tasks endpoint

- core/schema.py
Ticket: https://openimis.atlassian.net/browse/OTC-887
Changes:
- Added regex check to validate email address.
> OTC-887: Regex check for email validity.

- core/schema.py
https://openimis.atlassian.net/browse/OP-1366
This PR adds show historical data option to users.
It needs this PR: https://github.com/openimis/openimis-fe-admin_js/pull/64
> OP-1366: add showHistory filtering

- core/schema.py
Ticket: https://openimis.atlassian.net/browse/OTC-887
Changes:
- Changed email regex to be consistent with FE.
> OTC-887: Email validation regex updated.

- core/schema.py
- core/utils.py
https://openimis.atlassian.net/browse/OP-1433
This PR flattens config dict to get all the nested permissions.
It is a part of: https://github.com/openimis/openimis-be-api_fhir_r4_py/pull/128
> OSD-295: flatten the config dict to get all of the perms

- core/schema.py
Ticket: https://openimis.atlassian.net/browse/OP-1416
Changes:
- Email is now required when new user is created.
> OP-1416: Email is now required when creating new user.

- core/migrations/0019_extended_field.py
- core/models.py
https://openimis.atlassian.net/browse/OTC-1077
> OTC-1077: Extend the officer model 

- core/schema.py
[RELATED FE](https://github.com/openimis/openimis-fe-admin_js/pull/71)
[OTC-1082](https://openimis.atlassian.net/browse/OTC-1082)
Changes:
- Add _parent_location_ and _parent_location_level_ args to be able to use filters in a default way (like in insurees/ premiums) and enable resetting search location fields.
[OTC-1082]: https://openimis.atlassian.net/browse/OTC-1082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OTC-1082: add parent_location logic to users query

- core/gql/export_mixin.py
- core/models.py
Issues discovered during work on [CM-29](https://openimis.atlassian.net/browse/CM-29). 
* Fixed data filtering 
* Fixed flexible columns added through patching functionality 
[CM-29]: https://openimis.atlassian.net/browse/CM-29?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CM-29: Fixed generic export

- core/custom_filters/custom_filter_wizard_interface.py
- core/gql/export_mixin.py
part of ticket: https://openimis.atlassian.net/browse/CM-71
- added additional interface for applying custom filters provided from frontend level into Django queryset
> CM-71: added interface for applying queryset based on custom filters provided by frontend, extend export to add custom filters

- core/models.py
[https://openimis.atlassian.net/jira/software/projects/CM/issues/CM-206](https://openimis.atlassian.net/jira/software/projects/CM/issues/CM-206)
> CM-206 Fixed User is_imis_administrator property

- core/utils.py
Ticket [here](https://openimis.atlassian.net/browse/OP-1478)
> OP-1478 - Fixed existing role search

- core/services/utils/serviceUtils.py
[https://openimis.atlassian.net/browse/CM-188](https://openimis.atlassian.net/browse/CM-188)
> CM-188 Adjusted backend for social protection

- core/utils.py
https://openimis.atlassian.net/browse/CM-210
Adds functions that converts strings to python values.
> CM-210: add convert to python utils

- core/services/userServices.py
Ticket: https://openimis.atlassian.net/browse/ONI-138
Changes:
- Fixing checks during creating/editing of an user.
- An error is no longer thrown.
> ONI-138: User editing fix.

- core/services/base.py
[https://openimis.atlassian.net/browse/CM-229](https://openimis.atlassian.net/browse/CM-229)
> CM-229 Updated __init__ of BaseService

- core/apps.py
- core/jwt_authentication.py
Ticket: https://openimis.atlassian.net/browse/ONI-104
FE PR: https://github.com/openimis/openimis-fe-core_js/pull/158
Changes:
- Added error code for invalid HF status
> ONI-104: Block logging if HF contract expired.

- core/services/userServices.py
Ticket: https://openimis.atlassian.net/browse/ONI-174
Changes:
- Fixed updating user roles - CA and EO
> ONI-174: Fix updating user.

- core/serializers.py
https://openimis.atlassian.net/browse/OM-70
> OM-70: serialize user roles

- core/serializers.py
Reverts openimis/openimis-be-core_py#230, We don't need that
> Revert "OM-70: serialize user roles"

- core/apps.py
- core/management/commands/generateusers.py
- core/models.py
- core/schema.py
- core/utils.py
MERGING RELEASE branches
Release release/23.10
> MERGING develop into release/23.10

- core/models.py
- core/schema.py
https://openimis.atlassian.net/browse/OP-1773
Changed the authentication to handle case-insensitivity of a username
> OP-1733: Login doesn't work in Postgres because of the case-sensitivity

- core/jwt_authentication.py
Ticket: https://openimis.atlassian.net/browse/ONI-104
FE PR: https://github.com/openimis/openimis-fe-core_js/pull/158
Changes:
- Error code now sent to frontend
- Frontend now can show different messages for different reasons of discarding authentication
> ONI-104: Draft for new auth system.

- core/utils.py
https://openimis.atlassian.net/browse/CM-465
> CM-465: add check uuid to utils

- core/apps.py
- core/serializers.py
- core/services/userServices.py
[https://openimis.atlassian.net/browse/OM-80](https://openimis.atlassian.net/browse/OM-80)
> OM-80 Added has_password to i_user serializer

- core/utils.py
- locale/en/LC_MESSAGES/django.po
- setup.py
https://openimis.atlassian.net/browse/CM-497
> CM-497: move schema validation to core

- core/gql/export_mixin.py
[https://openimis.atlassian.net/browse/OM-119](https://openimis.atlassian.net/browse/OM-119)
> OM-119 Fixed resolve args vs filter args

- core/models.py
TICKET: [CM-733](https://openimis.atlassian.net/browse/CM-733)
[CM-733]: https://openimis.atlassian.net/browse/CM-733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CM-733: Fixed export from query bug

- core/utils.py
https://openimis.atlassian.net/browse/CM-508
It adds util that helps with handling of files.
> CM-508: add file handler util

- core/security.py
https://openimis.atlassian.net/browse/OP-1815
> OP-1815: Move checkUserWithRights to core from tools

- core/utils.py
https://openimis.atlassian.net/browse/CM-504
Used in: https://github.com/openimis/openimis-be-payroll_py/pull/42
> CM-504: add file path check

- core/apps.py
- core/schema.py
- core/services/utils/serviceUtils.py
[https://openimis.atlassian.net/browse/OM-130](https://openimis.atlassian.net/browse/OM-130)
> OM-130 Added possibility to block username change

- core/apps.py
[https://openimis.atlassian.net/browse/OM-130](https://openimis.atlassian.net/browse/OM-130)
> OM-130 Fixed broken config

- core/apps.py
- core/models.py
[https://openimis.atlassian.net/jira/software/projects/OM/issues/OM-130](https://openimis.atlassian.net/jira/software/projects/OM/issues/OM-130)
> OM-130 Fixed wrong config usage

- core/utils.py
https://openimis.atlassian.net/browse/CM-700
> CM-700: add remove file util

- core/utils.py
- core/validation/stringFieldValidationMixin.py
- locale/en/LC_MESSAGES/django.po
https://openimis.atlassian.net/browse/CM-742
> CM-742: add string field validation mixin

- core/__init__.py
- core/custom_lookups.py
- core/utils.py
- core/validation/__init__.py
- core/validation/stringFieldValidationMixin.py
- locale/en/LC_MESSAGES/django.po
MERGING develop into release/24.04
> MERGING develop into release/24.04

- core/apps.py
async_mutation is now based on the environment variable. False if mode is DEV otherwise True in PROD
> async_mutation now relies on the env variable MODE

- core/schema.py
[OP-1825](https://openimis.atlassian.net/browse/OP-1825)
[FE PR](https://github.com/openimis/openimis-fe-core_js/pull/217)
Changes:
- Add possibility to filter roles using role right.
[OP-1825]: https://openimis.atlassian.net/browse/OP-1825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1825: role right filter on role query

- core/validation/objectExistsValidationMixin.py
> hotfix-filter-exists

- core/jwt_authentication.py
Ticket: https://openimis.atlassian.net/browse/OP-2035
Changes:
- Raising exception instead of returning none allows to show proper information on the frontend
> OP-2035: Returning exception instead of null when no token provided.

- core/apps.py
- core/schema.py
Ticket:
https://openimis.atlassian.net/browse/CQI-149
Changes:
- set up password policy in core config to available fetching it in FE app
> CQI-149: config for password policy added to Query

- core/models/user.py
- core/utils.py
- setup.py
Password Validator is off when MODE is not PROD
> Validator is off when MODE is not PROD

- core/middleware.py
Ticket:
https://openimis.atlassian.net/browse/CQI-157
Related:
https://github.com/openimis/openimis-be_py/pull/256
Changes:
- new middleware is added to set security headers that cannot be set directly in settings.py
> CQI-157: added security header middleware

- core/jwt.py
Ticket:
https://openimis.atlassian.net/browse/CQI-165
Changes:
-     RS256 is set when keys are available, if not HS256 is used
-     Added jti (JSON Web Token ID)
-     Added nbf (not before, claim identifies the time before which the JWT MUST NOT be accepted for processing)
Logged in as user, authentication works.
> CQI-165: use RS256 and enchance JWT

- core/schema.py
- core/services/userServices.py
Ticket:
https://openimis.atlassian.net/browse/CQI-150
Changes:
- axes now handles reset password functionality logs too
- added lockout mechanism for reset password functionality
> CQI-150: added lockout mechanism for reset password functionality

- core/schema.py
Ticket:
https://openimis.atlassian.net/browse/CQI-159
Related:
https://github.com/openimis/openimis-fe-core_js/pull/228
Changes:
- middleware for csrf token check is used in request that results in obtaining JWT token, so without JWT we have to validate XCSRFToken
1. Login works
2. Intercept csrf token and modified in burp suite does not work
3. Other requests work without issues
> CQI-159: added csrf token handling with middleware for login request

- core/jwt_authentication.py
- core/middleware.py
- core/schema.py
- core/services/userServices.py
- setup.py
Ticket:
https://openimis.atlassian.net/browse/CQI-156
Changes:
- added rate limiter which has higher numbers than lockout mechanism
If user make to many request he will get 429 error page and server will not accept requests from him until the limit is over.
> CQI-156: added rate limiter

- core/models/openimis_graphql_test_case.py
- core/schema.py
- core/tests/test_graphql.py
Ticket: https://openimis.atlassian.net/browse/OM-182
Changes:
- Added mutation to change user language
- Only works for current user for security reasons
> OM-182: Added user language change mutation.
